---
driver_plugin: digitalocean
driver_config:
  size: 4GB
  require_chef_omnibus: latest

platforms:
- name: debian-8.2
  provisioner:
    sudo: false
  busser:
    sudo: false
- name: ubuntu-14-04-x64
  provisioner:
    sudo: false
  busser:
    sudo: false
- name: ubuntu-16-04-x64
  provisioner:
    sudo: false
  busser:
    sudo: false
- name: centos-7-0-x64
  provisioner:
    sudo: false
  busser:
    sudo: false

suites:
  - name: default
    run_list:
    - recipe[rocketchat]
    attributes:
