AllCops:
  Exclude:
    - bin/**/*
    - cookbooks/**/*
    - tmp/**/*
    - vendor/**/*

AlignParameters:
  Enabled: false
BlockLength:
  Exclude:
    - spec/unit/attributes_spec.rb
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 30
SpaceBeforeFirstArg:
  Enabled: false
